source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'TKit_Example' do
  pod "TK", :path => "../"
end

#target 'TKit_Tests' do
#  pod "TK", :path => "../"
#
#  pod 'Quick'
#  pod 'Nimble'
#end
