source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TKit_Example', :exclusive => true do
  pod "TK", :path => "../"
end

target 'TKit_Tests', :exclusive => true do
  pod "TK", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end
